In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/batsman-diabetes-ipl-movies/movies (1).csv
/kaggle/input/batsman-diabetes-ipl-movies/batsman_runs_ipl.csv
/kaggle/input/batsman-diabetes-ipl-movies/ipl-matches.csv
/kaggle/input/batsman-diabetes-ipl-movies/diabetes.csv

In [2]:
import numpy as np
import pandas as pd

# Creating Dataframes

In [4]:
#Using Lists
students_info=[[100,90,20],
               [90,80,10],
              [80,75,19],
              [80,70,18]]
pd.DataFrame(students_info,columns=['iq','marks','package'])

    iq  marks  package
0  100     90       20
1   90     80       10
2   80     75       19
3   80     70       18

In [6]:
# using dictionary
student_info={'iq':[100,90,80,80],
             'marks':[90,80,75,70],
             'package':[20,10,19,18]}
st=pd.DataFrame(student_info)
print(st)

    iq  marks  package
0  100     90       20
1   90     80       10
2   80     75       19
3   80     70       18

In [7]:
#using csv
movies_df=pd.read_csv('/kaggle/input/batsman-diabetes-ipl-movies/movies (1).csv')
movies_df.head()

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)

In [8]:
Ipl_df=pd.read_csv('/kaggle/input/batsman-diabetes-ipl-movies/ipl-matches.csv')
Ipl_df.head()

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan

# DataFrame Attibutes and Methods

In [9]:
#Shape of the dataframe
Ipl_df.shape

(950, 20)

In [13]:
#tells about the datatype of the dtaframe
Ipl_df.dtypes

ID                   int64
City                object
Date                object
Season              object
MatchNumber         object
Team1               object
Team2               object
Venue               object
TossWinner          object
TossDecision        object
SuperOver           object
WinningTeam         object
WonBy               object
Margin             float64
method              object
Player_of_Match     object
Team1Players        object
Team2Players        object
Umpire1             object
Umpire2             object
dtype: object

In [12]:
movies_df.shape

(1629, 18)

In [10]:
movies_df.dtypes

title_x              object
imdb_id              object
poster_path          object
wiki_link            object
title_y              object
original_title       object
is_adult              int64
year_of_release       int64
runtime              object
genres               object
imdb_rating         float64
imdb_votes            int64
story                object
summary              object
tagline              object
actors               object
wins_nominations     object
release_date         object
dtype: object

In [14]:
#index of the dataset
movies_df.index

RangeIndex(start=0, stop=1629, step=1)

In [15]:
#column names
movies_df.columns

Index(['title_x', 'imdb_id', 'poster_path', 'wiki_link', 'title_y',
       'original_title', 'is_adult', 'year_of_release', 'runtime', 'genres',
       'imdb_rating', 'imdb_votes', 'story', 'summary', 'tagline', 'actors',
       'wins_nominations', 'release_date'],
      dtype='object')

In [16]:
#values
movies_df.values

array([['Uri: The Surgical Strike', 'tt8291224',
        'https://upload.wikimedia.org/wikipedia/en/thumb/3/3b/URI_-_New_poster.jpg/220px-URI_-_New_poster.jpg',
        ...,
        'Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Gautam|Kirti Kulhari|Rajit Kapoor|Ivan Rodrigues|Manasi Parekh|Swaroop Sampat|Riva Arora|Yogesh Soman|Fareed Ahmed|Akashdeep Arora|Kallol Banerjee|',
        '4 wins', '11 January 2019 (USA)'],
       ['Battalion 609', 'tt9472208', nan, ...,
        'Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elena Kazan|Vishwas Kini|Major Kishore|Jashn Kohli|Rammy C. Pandey|Manish Sharma|Sparsh Sharma|Farnaz Shetty|Vikas Shrivastav|Chandraprakash Thakur|Brajesh Tiwari|',
        nan, '11 January 2019 (India)'],
       ['The Accidental Prime Minister (film)', 'tt6986710',
        'https://upload.wikimedia.org/wikipedia/en/thumb/a/a1/The_Accidental_Prime_Minister_film.jpg/220px-The_Accidental_Prime_Minister_film.jpg',
        ...,
        'Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul Sharma|Manoj Anand|Arjun Mathur|Suzanne Bernert|Abdul Quadir Amin|Bharat Mistri|Divya Seth|Anil Rastogi|Ramesh Bhatkar|Parrgash Kaur|Jess Kaur|',
        nan, '11 January 2019 (USA)'],
       ...,
       ['Sabse Bada Sukh', 'tt0069204', nan, ...,
        'Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpal Dutt|Meeta Faiyyaz|Rabi Ghosh|Tarun Ghosh|Sanjeev Kumar|Keshto Mukherjee|Meena Rai|',
        nan, nan],
       ['Daaka', 'tt10833860',
        'https://upload.wikimedia.org/wikipedia/en/thumb/4/45/Daaka.jpg/220px-Daaka.jpg',
        ..., 'Gippy Grewal|Zareen Khan|', nan, '1 November 2019 (USA)'],
       ['Humsafar', 'tt2403201',
        'https://upload.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/23px-Flag_of_India.svg.png',
        ..., 'Fawad Khan|', nan, 'TV Series (2011–2012)']], dtype=object)

In [17]:
#head and tail 
movies_df.head()

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)

In [18]:
movies_df.tail()

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
1624,Tera Mera Saath Rahen,tt0301250,https://upload.wikimedia.org/wikipedia/en/2/2b...,https://en.wikipedia.org/wiki/Tera_Mera_Saath_...,Tera Mera Saath Rahen,Tera Mera Saath Rahen,0,2001,148,Drama,4.9,278,Raj Dixit lives with his younger brother Rahu...,A man is torn between his handicapped brother ...,NaN,Ajay Devgn|Sonali Bendre|Namrata Shirodkar|Pre...,NaN,7 November 2001 (India)
1625,Yeh Zindagi Ka Safar,tt0298607,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Yeh_Zindagi_Ka_S...,Yeh Zindagi Ka Safar,Yeh Zindagi Ka Safar,0,2001,146,Drama,3.0,133,Hindi pop-star Sarina Devan lives a wealthy ...,A singer finds out she was adopted when the ed...,NaN,Ameesha Patel|Jimmy Sheirgill|Nafisa Ali|Gulsh...,NaN,16 November 2001 (India)
1626,Sabse Bada Sukh,tt0069204,NaN,https://en.wikipedia.org/wiki/Sabse_Bada_Sukh,Sabse Bada Sukh,Sabse Bada Sukh,0,2018,\N,Comedy|Drama,6.1,13,Village born Lalloo re-locates to Bombay and ...,Village born Lalloo re-locates to Bombay and ...,NaN,Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpa...,NaN,NaN
1627,Daaka,tt10833860,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Daaka,Daaka,Daaka,0,2019,136,Action,7.4,38,Shinda tries robbing a bank so he can be wealt...,Shinda tries robbing a bank so he can be wealt...,NaN,Gippy Grewal|Zareen Khan|,NaN,1 November 2019 (USA)
1628,Humsafar,tt2403201,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Humsafar,Humsafar,Humsafar,0,2011,35,Drama|Romance,9.0,2968,Sara and Ashar are childhood friends who share...,Ashar and Khirad are forced to get married due...,NaN,Fawad Khan|,NaN,TV Series (2011–2012)

In [19]:
# sample function
movies_df.sample

<bound method NDFrame.sample of                                    title_x     imdb_id  \
0                 Uri: The Surgical Strike   tt8291224
1                            Battalion 609   tt9472208
2     The Accidental Prime Minister (film)   tt6986710
3                          Why Cheat India   tt8108208
4                          Evening Shadows   tt6028796
...                                    ...         ...
1624                 Tera Mera Saath Rahen   tt0301250
1625                  Yeh Zindagi Ka Safar   tt0298607
1626                       Sabse Bada Sukh   tt0069204
1627                                 Daaka  tt10833860
1628                              Humsafar   tt2403201

                                            poster_path  \
0     https://upload.wikimedia.org/wikipedia/en/thum...
1                                                   NaN
2     https://upload.wikimedia.org/wikipedia/en/thum...
3     https://upload.wikimedia.org/wikipedia/en/thum...
4                                                   NaN
...                                                 ...
1624  https://upload.wikimedia.org/wikipedia/en/2/2b...
1625  https://upload.wikimedia.org/wikipedia/en/thum...
1626                                                NaN
1627  https://upload.wikimedia.org/wikipedia/en/thum...
1628  https://upload.wikimedia.org/wikipedia/en/thum...

                                              wiki_link  \
0     https://en.wikipedia.org/wiki/Uri:_The_Surgica...
1           https://en.wikipedia.org/wiki/Battalion_609
2     https://en.wikipedia.org/wiki/The_Accidental_P...
3         https://en.wikipedia.org/wiki/Why_Cheat_India
4         https://en.wikipedia.org/wiki/Evening_Shadows
...                                                 ...
1624  https://en.wikipedia.org/wiki/Tera_Mera_Saath_...
1625  https://en.wikipedia.org/wiki/Yeh_Zindagi_Ka_S...
1626      https://en.wikipedia.org/wiki/Sabse_Bada_Sukh
1627                https://en.wikipedia.org/wiki/Daaka
1628             https://en.wikipedia.org/wiki/Humsafar

                            title_y                 original_title  is_adult  \
0          Uri: The Surgical Strike       Uri: The Surgical Strike         0
1                     Battalion 609                  Battalion 609         0
2     The Accidental Prime Minister  The Accidental Prime Minister         0
3                   Why Cheat India                Why Cheat India         0
4                   Evening Shadows                Evening Shadows         0
...                             ...                            ...       ...
1624          Tera Mera Saath Rahen          Tera Mera Saath Rahen         0
1625           Yeh Zindagi Ka Safar           Yeh Zindagi Ka Safar         0
1626                Sabse Bada Sukh                Sabse Bada Sukh         0
1627                          Daaka                          Daaka         0
1628                       Humsafar                       Humsafar         0

      year_of_release runtime            genres  imdb_rating  imdb_votes  \
0                2019     138  Action|Drama|War          8.4       35112
1                2019     131               War          4.1          73
2                2019     112   Biography|Drama          6.1        5549
3                2019     121       Crime|Drama          6.0        1891
4                2018     102             Drama          7.3         280
...               ...     ...               ...          ...         ...
1624             2001     148             Drama          4.9         278
1625             2001     146             Drama          3.0         133
1626             2018      \N      Comedy|Drama          6.1          13
1627             2019     136            Action          7.4          38
1628             2011      35     Drama|Romance          9.0        2968

                                                  story  \
0     Divided over five chapters  the film chronicle...
1     The story revolves around a cricket match betw...
2     Based on the memoir by Indian policy analyst S...
3     The movie focuses on existing malpractices in ...
4     While gay rights and marriage equality has bee...
...                                                 ...
1624  Raj Dixit lives with his younger brother  Rahu...
1625  Hindi pop-star  Sarina Devan  lives a wealthy ...
1626  Village born Lalloo re-locates to Bombay  and ...
1627  Shinda tries robbing a bank so he can be wealt...
1628  Sara and Ashar are childhood friends who share...

                                                summary tagline  \
0     Indian army special forces execute a covert op...     NaN
1     The story of Battalion 609 revolves around a c...     NaN
2     Explores Manmohan Singh's tenure as the Prime ...     NaN
3     The movie focuses on existing malpractices in ...     NaN
4     Under the 'Evening Shadows'  truth often plays...     NaN
...                                                 ...     ...
1624  A man is torn between his handicapped brother ...     NaN
1625  A singer finds out she was adopted when the ed...     NaN
1626  Village born Lalloo re-locates to Bombay  and ...     NaN
1627  Shinda tries robbing a bank so he can be wealt...     NaN
1628  Ashar and Khirad are forced to get married due...     NaN

                                                 actors  \
0     Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...
1     Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...
2     Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...
3     Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...
4     Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...
...                                                 ...
1624  Ajay Devgn|Sonali Bendre|Namrata Shirodkar|Pre...
1625  Ameesha Patel|Jimmy Sheirgill|Nafisa Ali|Gulsh...
1626  Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpa...
1627                          Gippy Grewal|Zareen Khan|
1628                                        Fawad Khan|

            wins_nominations              release_date
0                     4 wins     11 January 2019 (USA)
1                        NaN   11 January 2019 (India)
2                        NaN     11 January 2019 (USA)
3                        NaN     18 January 2019 (USA)
4     17 wins & 1 nomination   11 January 2019 (India)
...                      ...                       ...
1624                     NaN   7 November 2001 (India)
1625                     NaN  16 November 2001 (India)
1626                     NaN                       NaN
1627                     NaN     1 November 2019 (USA)
1628                     NaN     TV Series (2011–2012)

[1629 rows x 18 columns]>

In [20]:
movies_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1629 entries, 0 to 1628
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   title_x           1629 non-null   object
 1   imdb_id           1629 non-null   object
 2   poster_path       1526 non-null   object
 3   wiki_link         1629 non-null   object
 4   title_y           1629 non-null   object
 5   original_title    1629 non-null   object
 6   is_adult          1629 non-null   int64
 7   year_of_release   1629 non-null   int64
 8   runtime           1629 non-null   object
 9   genres            1629 non-null   object
 10  imdb_rating       1629 non-null   float64
 11  imdb_votes        1629 non-null   int64
 12  story             1609 non-null   object
 13  summary           1629 non-null   object
 14  tagline           557 non-null    object
 15  actors            1624 non-null   object
 16  wins_nominations  707 non-null    object
 17  release_date      1522 non-null   object
dtypes: float64(1), int64(3), object(14)
memory usage: 229.2+ KB

In [22]:
# describe
movies_df.describe()

       is_adult  year_of_release  imdb_rating     imdb_votes
count    1629.0      1629.000000  1629.000000    1629.000000
mean        0.0      2010.263966     5.557459    5384.263352
std         0.0         5.381542     1.567609   14552.103231
min         0.0      2001.000000     0.000000       0.000000
25%         0.0      2005.000000     4.400000     233.000000
50%         0.0      2011.000000     5.600000    1000.000000
75%         0.0      2015.000000     6.800000    4287.000000
max         0.0      2019.000000     9.400000  310481.000000

In [26]:
#isnull
movies_df.isnull()

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
1,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False
4,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1624,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False
1625,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False
1626,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,True,True
1627,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False
1628,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False

In [27]:
#isnull().sum()
movies_df.isnull().sum()

title_x                0
imdb_id                0
poster_path          103
wiki_link              0
title_y                0
original_title         0
is_adult               0
year_of_release        0
runtime                0
genres                 0
imdb_rating            0
imdb_votes             0
story                 20
summary                0
tagline             1072
actors                 5
wins_nominations     922
release_date         107
dtype: int64

In [28]:
#duplicated
movies_df.duplicated().sum()

0

In [32]:
st=pd.DataFrame(student_info)
print(st)

    iq  marks  package
0  100     90       20
1   90     80       10
2   80     75       19
3   80     70       18

In [36]:
#rename, but not permanent change in the original dataset
st.rename(columns={'marks':'percent','package':'lpa'})

    iq  percent  lpa
0  100       90   20
1   90       80   10
2   80       75   19
3   80       70   18

In [37]:
#rename and permanent change
st.rename(columns={'marks':'percent','package':'lpa'},inplace=True)

In [35]:
st

    iq  percent  lpa
0  100       90   20
1   90       80   10
2   80       75   19
3   80       70   18

# Mathematical methods

In [39]:
# Sum:it applies sum function on all the columns or series of the dataframe
st.sum()

iq         350
percent    315
lpa         67
dtype: int64

In [40]:
st.sum(axis=1)

0    210
1    180
2    174
3    168
dtype: int64

In [41]:
st.median()

iq         85.0
percent    77.5
lpa        18.5
dtype: float64

In [42]:
st.mean()

iq         87.50
percent    78.75
lpa        16.75
dtype: float64

In [43]:
st.min()

iq         80
percent    70
lpa        10
dtype: int64

In [44]:
st.max()

iq         100
percent     90
lpa         20
dtype: int64

In [45]:
st.var()

iq         91.666667
percent    72.916667
lpa        20.916667
dtype: float64

# Selecting perticular column from the dataframe

In [46]:
st['iq']

0    100
1     90
2     80
3     80
Name: iq, dtype: int64

In [47]:
movies_df

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1624,Tera Mera Saath Rahen,tt0301250,https://upload.wikimedia.org/wikipedia/en/2/2b...,https://en.wikipedia.org/wiki/Tera_Mera_Saath_...,Tera Mera Saath Rahen,Tera Mera Saath Rahen,0,2001,148,Drama,4.9,278,Raj Dixit lives with his younger brother Rahu...,A man is torn between his handicapped brother ...,NaN,Ajay Devgn|Sonali Bendre|Namrata Shirodkar|Pre...,NaN,7 November 2001 (India)
1625,Yeh Zindagi Ka Safar,tt0298607,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Yeh_Zindagi_Ka_S...,Yeh Zindagi Ka Safar,Yeh Zindagi Ka Safar,0,2001,146,Drama,3.0,133,Hindi pop-star Sarina Devan lives a wealthy ...,A singer finds out she was adopted when the ed...,NaN,Ameesha Patel|Jimmy Sheirgill|Nafisa Ali|Gulsh...,NaN,16 November 2001 (India)
1626,Sabse Bada Sukh,tt0069204,NaN,https://en.wikipedia.org/wiki/Sabse_Bada_Sukh,Sabse Bada Sukh,Sabse Bada Sukh,0,2018,\N,Comedy|Drama,6.1,13,Village born Lalloo re-locates to Bombay and ...,Village born Lalloo re-locates to Bombay and ...,NaN,Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpa...,NaN,NaN
1627,Daaka,tt10833860,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Daaka,Daaka,Daaka,0,2019,136,Action,7.4,38,Shinda tries robbing a bank so he can be wealt...,Shinda tries robbing a bank so he can be wealt...,NaN,Gippy Grewal|Zareen Khan|,NaN,1 November 2019 (USA)
1628,Humsafar,tt2403201,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Humsafar,Humsafar,Humsafar,0,2011,35,Drama|Romance,9.0,2968,Sara and Ashar are childhood friends who share...,Ashar and Khirad are forced to get married due...,NaN,Fawad Khan|,NaN,TV Series (2011–2012)

In [48]:
#fetching single column of feature 
movies_df['title_x']

0                   Uri: The Surgical Strike
1                              Battalion 609
2       The Accidental Prime Minister (film)
3                            Why Cheat India
4                            Evening Shadows
                        ...
1624                   Tera Mera Saath Rahen
1625                    Yeh Zindagi Ka Safar
1626                         Sabse Bada Sukh
1627                                   Daaka
1628                                Humsafar
Name: title_x, Length: 1629, dtype: object

In [52]:

type(movies_df['title_x'])

pandas.core.series.Series

In [51]:
#fetch multiple columns
movies_df[['title_x',"imdb_id","poster_path"]]

,title_x,imdb_id,poster_path
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...
1,Battalion 609,tt9472208,NaN
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...
4,Evening Shadows,tt6028796,NaN
...,...,...,...
1624,Tera Mera Saath Rahen,tt0301250,https://upload.wikimedia.org/wikipedia/en/2/2b...
1625,Yeh Zindagi Ka Safar,tt0298607,https://upload.wikimedia.org/wikipedia/en/thum...
1626,Sabse Bada Sukh,tt0069204,NaN
1627,Daaka,tt10833860,https://upload.wikimedia.org/wikipedia/en/thum...
1628,Humsafar,tt2403201,https://upload.wikimedia.org/wikipedia/en/thum...

# Fecting perticular row or rows from the dataframe
* iloc: search by the index position
* loc: search by index labels

In [55]:
student_info={'name':['harry','tom','rancho','kabir','rishi'],
    'iq':[100,90,80,80,89],
             'marks':[90,80,75,70,89],
             'package':[20,10,19,18,20]}
st=pd.DataFrame(student_info)
print(st)

     name   iq  marks  package
0   harry  100     90       20
1     tom   90     80       10
2  rancho   80     75       19
3   kabir   80     70       18
4   rishi   89     89       20

In [56]:
st.set_index('name',inplace=True)
st

         iq  marks  package
name
harry   100     90       20
tom      90     80       10
rancho   80     75       19
kabir    80     70       18
rishi    89     89       20

In [60]:
#iloc : fectching a perticular row by index number
#fetching a single row, it will a series data
st.iloc[0] 
st.iloc[1]
st.iloc[2]

iq         80
marks      75
package    19
Name: rancho, dtype: int64

In [62]:
#fecthing multiple rows: it will a dataframe containg the specified rows
st.iloc[0:3]
st.iloc[3:]

       iq  marks  package
name
kabir  80     70       18
rishi  89     89       20

In [64]:
#skip alternate rows
st.iloc[::2]

         iq  marks  package
name
harry   100     90       20
rancho   80     75       19
rishi    89     89       20

In [65]:
#loc:fetching rows using lable name
st.loc['tom']

iq         90
marks      80
package    10
Name: tom, dtype: int64

In [66]:
st.loc['tom':'rishi']

        iq  marks  package
name
tom     90     80       10
rancho  80     75       19
kabir   80     70       18
rishi   89     89       20

In [67]:
st.loc['tom':'rishi':2]

       iq  marks  package
name
tom    90     80       10
kabir  80     70       18

In [69]:
#fancy  indexing 
st.loc[['tom','rishi']]

       iq  marks  package
name
tom    90     80       10
rishi  89     89       20

# Selecting data of perticular rows and columns

In [71]:
st.iloc[2:5,1:3] #2-5 rows and 1-3 columns

        marks  package
name
rancho     75       19
kabir      70       18
rishi      89       20

In [74]:
st.loc['rancho':'rishi','marks':'package'] #using labels of rows and columns

        marks  package
name
rancho     75       19
kabir      70       18
rishi      89       20

# Filtering the data from DataFrame

In [81]:
Ipl_df.head(2)

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon

In [84]:
# Find the winners of final match
mask=Ipl_df['MatchNumber']=="Final"
winninfg_df=Ipl_df[mask]
winninfg_df[['Season','WinningTeam','Player_of_Match']]

#or
Ipl_df[Ipl_df['MatchNumber']=="Final"][['Season','WinningTeam','Player_of_Match']]

      Season            WinningTeam Player_of_Match
0       2022         Gujarat Titans       HH Pandya
74      2021    Chennai Super Kings    F du Plessis
134  2020/21         Mumbai Indians        TA Boult
194     2019         Mumbai Indians       JJ Bumrah
254     2018    Chennai Super Kings       SR Watson
314     2017         Mumbai Indians       KH Pandya
373     2016    Sunrisers Hyderabad     BCJ Cutting
433     2015         Mumbai Indians       RG Sharma
492     2014  Kolkata Knight Riders       MK Pandey
552     2013         Mumbai Indians      KA Pollard
628     2012  Kolkata Knight Riders        MS Bisla
702     2011    Chennai Super Kings         M Vijay
775  2009/10    Chennai Super Kings        SK Raina
835     2009        Deccan Chargers        A Kumble
892  2007/08       Rajasthan Royals       YK Pathan

In [86]:
Ipl_df[Ipl_df['MatchNumber']=="Final"][['Season','WinningTeam','Player_of_Match']].reset_index()

    index   Season            WinningTeam Player_of_Match
0       0     2022         Gujarat Titans       HH Pandya
1      74     2021    Chennai Super Kings    F du Plessis
2     134  2020/21         Mumbai Indians        TA Boult
3     194     2019         Mumbai Indians       JJ Bumrah
4     254     2018    Chennai Super Kings       SR Watson
5     314     2017         Mumbai Indians       KH Pandya
6     373     2016    Sunrisers Hyderabad     BCJ Cutting
7     433     2015         Mumbai Indians       RG Sharma
8     492     2014  Kolkata Knight Riders       MK Pandey
9     552     2013         Mumbai Indians      KA Pollard
10    628     2012  Kolkata Knight Riders        MS Bisla
11    702     2011    Chennai Super Kings         M Vijay
12    775  2009/10    Chennai Super Kings        SK Raina
13    835     2009        Deccan Chargers        A Kumble
14    892  2007/08       Rajasthan Royals       YK Pathan

In [87]:
#number of superovers
Ipl_df[Ipl_df['SuperOver']=="Y"][['Season','WinningTeam','Player_of_Match']]

      Season                  WinningTeam Player_of_Match
114     2021               Delhi Capitals         PP Shaw
158  2020/21        Kolkata Knight Riders     LH Ferguson
159  2020/21              Kings XI Punjab        KL Rahul
184  2020/21  Royal Challengers Bangalore  AB de Villiers
192  2020/21               Delhi Capitals      MP Stoinis
203     2019               Mumbai Indians       JJ Bumrah
244     2019               Delhi Capitals         PP Shaw
339     2017               Mumbai Indians       KH Pandya
474     2015              Kings XI Punjab        SE Marsh
533     2014             Rajasthan Royals     JP Faulkner
608     2013  Royal Challengers Bangalore         V Kohli
621     2013          Sunrisers Hyderabad       GH Vihari
819  2009/10              Kings XI Punjab        J Theron
883     2009             Rajasthan Royals       YK Pathan

In [88]:
Ipl_df[Ipl_df['SuperOver']=="Y"].shape

(14, 20)

In [89]:
#matches won by csk

Ipl_df[Ipl_df['WinningTeam']=="Chennai Super Kings"].shape

(121, 20)

In [92]:
#matches won by csk in kolkata
Ipl_df[(Ipl_df['WinningTeam']=="Chennai Super Kings") & (Ipl_df['City']=='Kolkata')]

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
224,1178404,Kolkata,2019-04-14,2019,29,Kolkata Knight Riders,Chennai Super Kings,Eden Gardens,Chennai Super Kings,field,N,Chennai Super Kings,Wickets,5.0,NaN,Imran Tahir,"['CA Lynn', 'SP Narine', 'N Rana', 'RV Uthappa...","['SR Watson', 'F du Plessis', 'SK Raina', 'AT ...",CK Nandan,RJ Tucker
602,598022,Kolkata,2013-04-20,2013,26,Kolkata Knight Riders,Chennai Super Kings,Eden Gardens,Kolkata Knight Riders,bat,N,Chennai Super Kings,Wickets,4.0,NaN,RA Jadeja,"['G Gambhir', 'YK Pathan', 'JH Kallis', 'EJG M...","['MEK Hussey', 'R Ashwin', 'M Vijay', 'SK Rain...",Asad Rauf,AK Chaudhary
641,548368,Kolkata,2012-05-14,2012,63,Kolkata Knight Riders,Chennai Super Kings,Eden Gardens,Chennai Super Kings,field,N,Chennai Super Kings,Wickets,5.0,NaN,MEK Hussey,"['G Gambhir', 'BB McCullum', 'JH Kallis', 'MK ...","['MEK Hussey', 'M Vijay', 'SK Raina', 'F du Pl...",JD Cloete,SJA Taufel
827,419113,Kolkata,2010-03-16,2009/10,8,Kolkata Knight Riders,Chennai Super Kings,Eden Gardens,Chennai Super Kings,bat,N,Chennai Super Kings,Runs,55.0,NaN,MS Dhoni,"['BJ Hodge', 'MK Tiwary', 'SC Ganguly', 'WP Sa...","['M Vijay', 'ML Hayden', 'SK Raina', 'S Badrin...",HDPK Dharmasena,AM Saheba
908,336025,Kolkata,2008-05-18,2007/08,41,Kolkata Knight Riders,Chennai Super Kings,Eden Gardens,Kolkata Knight Riders,bat,N,Chennai Super Kings,Runs,3.0,D/L,M Ntini,"['Salman Butt', 'Mohammad Hafeez', 'SC Ganguly...","['PA Patel', 'SP Fleming', 'S Vidyut', 'SK Rai...",Asad Rauf,K Hariharan

In [94]:
#notice we used bitwise end because we are checking logical conditions
Ipl_df[(Ipl_df['WinningTeam']=="Chennai Super Kings") & (Ipl_df['City']=='Kolkata')].shape

(5, 20)

In [95]:
#to fetch number of rows only
Ipl_df[(Ipl_df['WinningTeam']=="Chennai Super Kings") & (Ipl_df['City']=='Kolkata')].shape[0]

5

In [97]:
#toss winner who won the match
Ipl_df[Ipl_df['TossWinner']==Ipl_df['WinningTeam']]

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
5,1304115,Mumbai,2022-05-21,2022,69,Delhi Capitals,Mumbai Indians,"Wankhede Stadium, Mumbai",Mumbai Indians,field,N,Mumbai Indians,Wickets,5.0,NaN,JJ Bumrah,"['PP Shaw', 'DA Warner', 'MR Marsh', 'RR Pant'...","['Ishan Kishan', 'RG Sharma', 'D Brevis', 'Til...",Nitin Menon,Tapan Sharma
8,1304112,Navi Mumbai,2022-05-18,2022,66,Lucknow Super Giants,Kolkata Knight Riders,"Dr DY Patil Sports Academy, Mumbai",Lucknow Super Giants,bat,N,Lucknow Super Giants,Runs,2.0,NaN,Q de Kock,"['Q de Kock', 'KL Rahul', 'E Lewis', 'DJ Hooda...","['VR Iyer', 'A Tomar', 'N Rana', 'SS Iyer', 'S...",R Pandit,YC Barde
11,1304109,Mumbai,2022-05-15,2022,63,Rajasthan Royals,Lucknow Super Giants,"Brabourne Stadium, Mumbai",Rajasthan Royals,bat,N,Rajasthan Royals,Runs,24.0,NaN,TA Boult,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['Q de Kock', 'KL Rahul', 'A Badoni', 'DJ Hood...",PG Pathak,Tapan Sharma
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
935,335996,Bangalore,2008-04-28,2007/08,15,Royal Challengers Bangalore,Chennai Super Kings,M Chinnaswamy Stadium,Chennai Super Kings,bat,N,Chennai Super Kings,Runs,13.0,NaN,MS Dhoni,"['B Chipli', 'W Jaffer', 'LRPL Taylor', 'JH Ka...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'SK Ra...",BR Doctrove,RB Tiffin
937,335994,Mumbai,2008-04-27,2007/08,14,Mumbai Indians,Deccan Chargers,Dr DY Patil Sports Academy,Deccan Chargers,field,N,Deccan Chargers,Wickets,10.0,NaN,AC Gilchrist,"['L Ronchi', 'ST Jayasuriya', 'AM Rahane', 'RV...","['AC Gilchrist', 'VVS Laxman', 'A Symonds', 'R...",Asad Rauf,SL Shastri
939,335992,Bangalore,2008-04-26,2007/08,12,Royal Challengers Bangalore,Rajasthan Royals,M Chinnaswamy Stadium,Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,SR Watson,"['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...","['GC Smith', 'M Rawat', 'YK Pathan', 'SR Watso...",MR Benson,IL Howell
941,335990,Hyderabad,2008-04-24,2007/08,9,Deccan Chargers,Rajasthan Royals,"Rajiv Gandhi International Stadium, Uppal",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,3.0,NaN,YK Pathan,"['AC Gilchrist', 'VVS Laxman', 'Shahid Afridi'...","['Kamran Akmal', 'GC Smith', 'YK Pathan', 'SR ...",Asad Rauf,MR Benson
948,335983,Chandigarh,2008-04-19,2007/08,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri

In [98]:
#toss winner who won the match in percentage
(Ipl_df[Ipl_df['TossWinner']==Ipl_df['WinningTeam']].shape[0]/Ipl_df.shape[0])*100

51.473684210526315

In [100]:
# movies with rating higher than 8 and votes>11000 
movies_df.head(1)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)

In [106]:
movies_df[(movies_df['imdb_rating']>8) & (movies_df['imdb_votes']>110000)].shape

(4, 18)

In [121]:
#action movies with rating>8
mask1=movies_df['genres'].str.split('|').apply(lambda x: 'Action' in x)
mask2=movies_df['imdb_rating']>9
movies_df[mask1 & mask2]

#or
movies_df[(movies_df['imdb_rating']>9) & (movies_df['genres'].str.split('|').apply(lambda x: 'Action' in x))]
#or
movies_df[(movies_df['imdb_rating']>9) & (movies_df['genres'].str.contains('Action'))]

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
41,Family of Thakurganj,tt8897986,https://upload.wikimedia.org/wikipedia/en/9/99...,https://en.wikipedia.org/wiki/Family_of_Thakur...,Family of Thakurganj,Family of Thakurganj,0,2019,127,Action|Drama,9.4,895,The film is based on small town of North India...,The film is based on small town of North India...,NaN,Jimmy Sheirgill|Mahie Gill|Nandish Singh|Prana...,NaN,19 July 2019 (India)

In [123]:
movies_df[(movies_df['imdb_rating']>9) & (movies_df['genres'].str.contains('Action'))].shape

(1, 18)

In [128]:
Ipl_df.Team1

0                 Rajasthan Royals
1      Royal Challengers Bangalore
2      Royal Challengers Bangalore
3                 Rajasthan Royals
4              Sunrisers Hyderabad
                  ...
945          Kolkata Knight Riders
946                 Mumbai Indians
947               Delhi Daredevils
948                Kings XI Punjab
949    Royal Challengers Bangalore
Name: Team1, Length: 950, dtype: object

In [131]:
#finding the track record of two teams
def track_record(team1,team2):
    team_record=Ipl_df[(Ipl_df['Team1']==team1) & (Ipl_df['Team2']==team2)]
    return team_record

In [132]:
track_record('Rajasthan Royals',"Delhi Daredevils")

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
308,1136566,Jaipur,2018-04-11,2018,6,Rajasthan Royals,Delhi Daredevils,Sawai Mansingh Stadium,Delhi Daredevils,field,N,Rajasthan Royals,Runs,10.0,D/L,SV Samson,"['AM Rahane', 'DJM Short', 'BA Stokes', 'SV Sa...","['GJ Maxwell', 'C Munro', 'RR Pant', 'CH Morri...",KN Ananthapadmanabhan,Nitin Menon
458,829777,Mumbai,2015-05-03,2015,36,Rajasthan Royals,Delhi Daredevils,Brabourne Stadium,Delhi Daredevils,field,N,Rajasthan Royals,Runs,14.0,NaN,AM Rahane,"['AM Rahane', 'SR Watson', 'KK Nair', 'JP Faul...","['MA Agarwal', 'SS Iyer', 'JP Duminy', 'Yuvraj...",HDPK Dharmasena,CB Gaffaney
511,734011,Ahmedabad,2014-05-15,2014,41,Rajasthan Royals,Delhi Daredevils,"Sardar Patel Stadium, Motera",Delhi Daredevils,field,N,Rajasthan Royals,Runs,62.0,NaN,AM Rahane,"['AM Rahane', 'KK Nair', 'KK Cooper', 'SV Sams...","['KP Pietersen', 'MA Agarwal', 'KD Karthik', '...",S Ravi,RJ Tucker
575,598049,Jaipur,2013-05-07,2013,52,Rajasthan Royals,Delhi Daredevils,Sawai Mansingh Stadium,Delhi Daredevils,bat,N,Rajasthan Royals,Wickets,9.0,NaN,AM Rahane,"['R Dravid', 'AM Rahane', 'SR Watson', 'SV Sam...","['DPMD Jayawardene', 'V Sehwag', 'CM Gautam', ...",Aleem Dar,RJ Tucker
661,548349,Jaipur,2012-05-01,2012,43,Rajasthan Royals,Delhi Daredevils,Sawai Mansingh Stadium,Rajasthan Royals,bat,N,Delhi Daredevils,Wickets,6.0,NaN,P Negi,"['R Dravid', 'AM Rahane', 'SR Watson', 'OA Sha...","['DPMD Jayawardene', 'V Sehwag', 'KP Pietersen...",JD Cloete,SJA Taufel
767,501204,Jaipur,2011-04-12,2011,7,Rajasthan Royals,Delhi Daredevils,Sawai Mansingh Stadium,Delhi Daredevils,bat,N,Rajasthan Royals,Wickets,6.0,NaN,SK Warne,"['AG Paunikar', 'R Dravid', 'J Botha', 'AL Men...","['DA Warner', 'V Sehwag', 'AJ Finch', 'UBT Cha...",Aleem Dar,RB Tiffin
829,419111,Ahmedabad,2010-03-15,2009/10,6,Rajasthan Royals,Delhi Daredevils,"Sardar Patel Stadium, Motera",Delhi Daredevils,field,N,Delhi Daredevils,Wickets,6.0,NaN,V Sehwag,"['SA Asnodkar', 'GC Smith', 'NV Ojha', 'YK Pat...","['G Gambhir', 'V Sehwag', 'TM Dilshan', 'AB de...",BG Jerling,RE Koertzen
917,336015,Jaipur,2008-05-11,2007/08,33,Rajasthan Royals,Delhi Daredevils,Sawai Mansingh Stadium,Rajasthan Royals,field,N,Rajasthan Royals,Wickets,3.0,NaN,SR Watson,"['YK Pathan', 'GC Smith', 'M Kaif', 'SR Watson...","['G Gambhir', 'V Sehwag', 'S Dhawan', 'AB de V...",SJ Davis,RE Koertzen

In [133]:
# adding new columns
st['class']='12th' #it will create class column with all values=12th

In [134]:
st

         iq  marks  package class
name
harry   100     90       20  12th
tom      90     80       10  12th
rancho   80     75       19  12th
kabir    80     70       18  12th
rishi    89     89       20  12th

In [143]:
Ipl_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               950 non-null    int64
 1   City             899 non-null    object
 2   Date             950 non-null    object
 3   Season           950 non-null    object
 4   MatchNumber      950 non-null    object
 5   Team1            950 non-null    object
 6   Team2            950 non-null    object
 7   Venue            950 non-null    object
 8   TossWinner       950 non-null    object
 9   TossDecision     950 non-null    object
 10  SuperOver        946 non-null    object
 11  WinningTeam      946 non-null    object
 12  WonBy            950 non-null    object
 13  Margin           932 non-null    float64
 14  method           19 non-null     object
 15  Player_of_Match  946 non-null    object
 16  Team1Players     950 non-null    object
 17  Team2Players     950 non-null    object
 18  Umpire1          950 non-null    object
 19  Umpire2          950 non-null    object
dtypes: float64(1), int64(1), object(18)
memory usage: 148.6+ KB

# astype: for changing the data type of any column

In [149]:

Ipl_df['ID']=Ipl_df['ID'].astype('int32')
Ipl_df['Margin']=Ipl_df['Margin'].astype('float32')

In [150]:
Ipl_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               950 non-null    int32
 1   City             899 non-null    object
 2   Date             950 non-null    object
 3   Season           950 non-null    object
 4   MatchNumber      950 non-null    object
 5   Team1            950 non-null    object
 6   Team2            950 non-null    object
 7   Venue            950 non-null    object
 8   TossWinner       950 non-null    object
 9   TossDecision     950 non-null    object
 10  SuperOver        946 non-null    object
 11  WinningTeam      946 non-null    object
 12  WonBy            950 non-null    object
 13  Margin           932 non-null    float32
 14  method           19 non-null     object
 15  Player_of_Match  946 non-null    object
 16  Team1Players     950 non-null    object
 17  Team2Players     950 non-null    object
 18  Umpire1          950 non-null    object
 19  Umpire2          950 non-null    object
dtypes: float32(1), int32(1), object(18)
memory usage: 141.1+ KB

In [153]:
Ipl_df['Season']=Ipl_df['Season'].astype('category')
Ipl_df['Team1']=Ipl_df['Team1'].astype('category')
Ipl_df['Team2']=Ipl_df['Team2'].astype('category')
Ipl_df['Team2']=Ipl_df['Team2'].astype('category')

In [154]:
Ipl_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               950 non-null    int32
 1   City             899 non-null    object
 2   Date             950 non-null    object
 3   Season           950 non-null    category
 4   MatchNumber      950 non-null    object
 5   Team1            950 non-null    category
 6   Team2            950 non-null    category
 7   Venue            950 non-null    object
 8   TossWinner       950 non-null    object
 9   TossDecision     950 non-null    object
 10  SuperOver        946 non-null    object
 11  WinningTeam      946 non-null    object
 12  WonBy            950 non-null    object
 13  Margin           932 non-null    float32
 14  method           19 non-null     object
 15  Player_of_Match  946 non-null    object
 16  Team1Players     950 non-null    object
 17  Team2Players     950 non-null    object
 18  Umpire1          950 non-null    object
 19  Umpire2          950 non-null    object
dtypes: category(3), float32(1), int32(1), object(15)
memory usage: 123.7+ KB